# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore CPSC-5260-Software-Refactoring-And-Design.slnx
    - name: Build
      run: dotnet build CPSC-5260-Software-Refactoring-And-Design.slnx --no-restore --configuration Release 
    - name: Test
      run: dotnet test CPSC-5260-Software-Refactoring-And-Design.slnx --no-build --configuration Release --verbosity normal --settings CompleteRunsettings.runsettings
